<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="funcWithReferences" Id="{d7eaaa47-cac1-4e5c-a960-7bf08f5055a0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION funcWithReferences : INT
VAR_IN_OUT
	num : INT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[num := num+1;]]></ST>
    </Implementation>
    <LineIds Name="funcWithReferences">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>