<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="sum" Id="{e8fd35ca-d14c-4be9-8dc0-c7a15e5f49f2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION sum : INT
VAR_INPUT
	num1 : INT;
	num2 : INT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[sum := num1 + num2;]]></ST>
    </Implementation>
    <LineIds Name="sum">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>