<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Motor" Id="{dbe739ed-a399-46b1-8792-527b21aebda7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Motor IMPLEMENTS IDevice
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	isOn : BOOL := FALSE;       
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="turnOn" Id="{6f161a4f-8a82-4c99-be1f-28c3318f397c}">
      <Declaration><![CDATA[METHOD PUBLIC turnOn
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[isOn := true;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="Motor">
      <LineId Id="12" Count="0" />
    </LineIds>
    <LineIds Name="Motor.turnOn">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>